feat: Customize WebDriver config in custom launcher
shaka-project/karma-local-wd-launcher pull request #35
Opened 2022-03-17 16:22 UTC by tykus160

Example of custom launcher with this PR:

```js
module.exports = function(config) {
  const firefoxOptions = {
    'moz:firefoxOptions': {
      prefs: {
        'media.eme.enabled': true,
        'media.gmp-manager.updateEnabled': true,
      },
    },
  };

  config.set({
    customLaunchers: {
      'FirefoxEME': {
        base: 'Firefox',
        config: firefoxOptions,
      },
      'FirefoxHeadlessEME': {
        base: 'FirefoxHeadless',
        config: firefoxOptions,
      },
    },
  });
};
```

2022-03-22 18:29 UTC, joeyparrish commented
I think this is really useful.  But for shaka-player, I think those settings you quote in the PR description should be the defaults for Firefox.

2022-03-22 18:32 UTC, joeyparrish requested changes
Thanks!

2022-03-22 18:32 UTC, joeyparrish commented on index.js
> +      _.merge(this.constructor.EXTRA_WEBDRIVER_SPECS, args.config);
Could you please document the `config` field in the Configuration section of the README?

Also, could you please add this to the EXTRA_WEBDRIVER_SPECS for Firefox launchers by default?

```js
    'moz:firefoxOptions': {
      prefs: {
        'media.eme.enabled': true,
        'media.gmp-manager.updateEnabled': true,
      },
    },
```

2022-03-23 15:57 UTC, tykus160 commented on index.js
> +      _.merge(this.constructor.EXTRA_WEBDRIVER_SPECS, args.config);
Done. I hope provided example is good enough.

2022-03-23 22:48 UTC, joeyparrish approved these changes
Thank you!

2022-03-23 22:52 UTC, merged